### ISSUE TITLE
Graal native image support

### ISSUE THREAD

**Issue by jeaye** [igrishaev/pg2#29]
Hi! I'm using pg2 in a project which I'd really like to compile into a native image for production. Unfortunately, due to pg2's resource URL usage, I'm currently blocked. Have you tried this at all?

The error I'm seeing is:

```
Exception in thread "main" java.lang.Error: Unsupported URL: resource:/migrations
	at pg.migration.fs$fn__2064.invokeStatic(fs.clj:39)
	at pg.migration.fs$fn__2064.invoke(fs.clj:37)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at pg.migration.core$url__GT_migrations.invokeStatic(core.clj:250)
```

I'm using lein-native-image with this config:
```clojure
             :native-image {:aot :all
                            :jvm-opts ["-Dclojure.compiler.direct-linking=true"]
                            :native-image {:name "bayaz"
                                           :opts ["--report-unsupported-elements-at-runtime"
                                                  "--initialize-at-build-time"
                                                  "--no-server"
                                                  "--initialize-at-run-time=org.apache"
                                                  "-H:+StaticExecutableWithDynamicLibC"
                                                  "-H:ResourceConfigurationFiles=resource-config.json"
                                                  "--enable-url-protocols=resource,file"
                                                  "--verbose"
                                                  "--no-fallback"]}}
```

I'm using this resource config in order to bring in the migrations:

```json
{
  "resources": {
    "includes": [
      {"pattern": "base-config.edn"},
      {"pattern": "migrations/.*"}
    ],
    "excludes": [
    ]
  }
}
```

All of this has been tried on Graal 23 community edition, on Linux x86_64.

According to this doc, the `resource` protocol should be enabled by default: https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/URLProtocols/ As you can see in my CLI flags, I also tried explicitly enabling it.

I'd be ok with `migrations` being read from a local dir instead of a resource. I'd also be ok with the resource working with native-image. Are you open to supporting either of these?

**Comment by igrishaev** [comment]
Thank you for reporting this, I'll take a look soon. From what I see now, the problem is mostly in the pg-migration package? Without it, does pg-core work fine in graal?

**Comment by jeaye** [comment]
Hey! Thanks for the quick response.

> Thank you for reporting this, I'll take a look soon. From what I see now, the problem is mostly in the pg-migration package? Without it, does pg-core work fine in graal?

Yep, this issue is with migrations. I haven't seen any other issues yet, but there may be some beyond this one. I'm optimistic this is the only issue. :slightly_smiling_face:

**Comment by igrishaev** [comment]
OK I've spotted the problem function, now trying to reproduce it locally.

**Comment by igrishaev** [comment]
Dear @jeaye ,
I think it has been fixed now. Can you try it please with a snapshot release  `0.1.28-SNAPSHOT`?

I refactored the pg-migration package. They key feature is, both `--config` and `--path` parameters are now considered not only as resources but files as well. The logic is, if the `--path` is `migrations`, first it tries to load a resource called `migrations`, and if it's missing, a local directory `migrations`. You can specify an absolute file path on your drive.

By the way, it looks like it's impossible to list files in a resource in GraalVM-compiled binary file. Thus, specifying a local directory is the only option, I think.

The changes weren't merged to master yet to ensure it works for you.

**Comment by igrishaev** [comment]
branch: https://github.com/igrishaev/pg2/tree/migrations-graal

**Comment by igrishaev** [comment]
Upd: rebased with master, now available as `0.1.29-SNAPSHOT`

**Comment by jeaye** [comment]
Nice! I'll try this out tomorrow. Thank you!

**Comment by jeaye** [comment]
It works! No issues. Thanks for the quick fix!
